language: c
compiler: clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpng-dev libjpeg-dev libblas-dev libgsl0-dev libblocksruntime-dev
script: cd lib && ./configure && make && cd ../test && make
